### ISSUE TITLE
csvDict vs pandas

### ISSUE THREAD

**Issue by alchemyst** [Stefan-Endres/DWPM-Mixture-Model#1]
Wouldn't a [pandas dataframe](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html) be a better option than the csvDict class?

**Comment by Stefan-Endres** [comment]
I will look into incorporating pandas. The only reason I used csvDict is because I didn't have internet access when I was working at Sappi, so I wrote something simple to handle data for me and kept using it in this project because I was comfortable with it.

I apologize for the disorganized state of that repository, I haven't documented anything other than the functions in Van_der_Waals.py because I kept replacing ones in binary.py and decided to wait until it was fully working.
